######################################################################
##
## Filename: tb_top.udo
## Created on: Sun Feb 16 12:00:50 Северная Центр. Азия (зима) 2014
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb_top/CLK_50MHZ
add wave -noupdate /tb_top/OSC_50MHZ
add wave -noupdate /tb_top/RESET_P
add wave -noupdate /tb_top/SYS_RST
add wave -noupdate /tb_top/SDATAP
add wave -noupdate /tb_top/DCOP
add wave -noupdate /tb_top/FCOP
add wave -noupdate /tb_top/ADC_CLKP

add wave -noupdate -divider {SYSTEM_I}
add wave -noupdate /tb_top/uut/s_clock

add wave -noupdate -divider {INFRASTRUCTURE}

add wave -noupdate /tb_top/uut/infrastructure_top_i/RESET_N
add wave -noupdate /tb_top/uut/infrastructure_top_i/clock
add wave -noupdate /tb_top/uut/infrastructure_top_i/clock40MHz
add wave -noupdate /tb_top/uut/infrastructure_top_i/hb25ns

add wave -noupdate -divider {TOP}
add wave -noupdate /tb_top/uut/s_clk_cnt
add wave -noupdate /tb_top/uut/s_adc_buf_wnum
add wave -noupdate /tb_top/uut/s_adc_data


add wave -noupdate -divider {ADC_CTRL}

add wave -noupdate /tb_top/uut/adc_ctrl_i/clock
add wave -noupdate /tb_top/uut/adc_ctrl_i/clock_locked
add wave -noupdate /tb_top/uut/adc_ctrl_i/clkp_cnt
add wave -noupdate /tb_top/uut/adc_ctrl_i/clkp_or
add wave -noupdate /tb_top/uut/adc_ctrl_i/s_clkp_div2
add wave -noupdate /tb_top/uut/adc_ctrl_i/hb25ns
add wave -noupdate /tb_top/uut/adc_ctrl_i/o_adc_data
add wave -noupdate /tb_top/uut/adc_ctrl_i/s_adc_buf_waddr
add wave -noupdate /tb_top/uut/adc_ctrl_i/s_adc_buf_wclk
add wave -noupdate /tb_top/uut/adc_ctrl_i/s_adc_buf_we
add wave -noupdate /tb_top/uut/adc_ctrl_i/s_adc_buf_we_ctrl
add wave -noupdate /tb_top/uut/adc_ctrl_i/i_adc_buf_we_ctrl
add wave -noupdate /tb_top/uut/adc_ctrl_i/s_adc_data_arr
add wave -noupdate /tb_top/uut/adc_ctrl_i/bitslip_reset
add wave -noupdate /tb_top/uut/adc_ctrl_i/s_clock40MHz
add wave -noupdate /tb_top/uut/adc_ctrl_i/s_clock40MHz_next
add wave -noupdate /tb_top/uut/adc_ctrl_i/s_adc_data_to_write
add wave -noupdate /tb_top/uut/adc_ctrl_i/s_adc_buf_wclk

add wave -noupdate -divider {ADC_DESER}

add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_DESER(1)/adc_deser/clock
add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_DESER(1)/adc_deser/s_clock_adc
add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_DESER(1)/adc_deser/DCOP
add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_DESER(1)/adc_deser/FCOP
add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_DESER(1)/adc_deser/dco_divclk
add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_DESER(1)/adc_deser/dco_strobe
add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_DESER(1)/adc_deser/dco_ib
add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_DESER(1)/adc_deser/ch1_data_sr
add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_DESER(1)/adc_deser/ch1_serdes_q
add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_DESER(1)/adc_deser/fco_serdes_q
add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_DESER(1)/adc_deser/fco_serdes_q_r
add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_DESER(1)/adc_deser/bit_slip_r
add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_DESER(1)/adc_deser/frame_start_r
add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_DESER(1)/adc_deser/data_we

add wave -noupdate -divider {LOM}
add wave -noupdate /tb_top/uut/lom_i/i_clock
add wave -noupdate /tb_top/uut/lom_i/i_adc_data
add wave -noupdate /tb_top/uut/lom_i/s_discr1
add wave -noupdate /tb_top/uut/lom_i/s_discr2
add wave -noupdate /tb_top/uut/lom_i/s_coin
add wave -noupdate /tb_top/uut/lom_i/s_hampl
add wave -noupdate /tb_top/uut/lom_i/s_hist_wena
add wave -noupdate /tb_top/uut/lom_i/s_hist_wena

add wave -noupdate -divider {AMPL}
add wave -noupdate /tb_top/uut/lom_i/AU/i_signal
add wave -noupdate /tb_top/uut/lom_i/AU/i_gate
add wave -noupdate /tb_top/uut/lom_i/AU/s_gate_prev
add wave -noupdate /tb_top/uut/lom_i/AU/s_gate_next

add wave -noupdate -divider {HIST}
add wave -noupdate /tb_top/uut/lom_i/HU/i_enable
add wave -noupdate /tb_top/uut/lom_i/HU/s_bin_data

add wave -noupdate -divider {SELFTEST}
add wave -noupdate /tb_top/uut/self_tester_i/HU/i_enable
add wave -noupdate /tb_top/uut/self_tester_i/HU/s_data_buf
add wave -noupdate /tb_top/uut/self_tester_i/HU/o_testbuf_addr
add wave -noupdate /tb_top/uut/self_tester_i/HU/o_testbuf_data
add wave -noupdate /tb_top/uut/self_tester_i/HU/s_is_initialized
add wave -noupdate /tb_top/uut/self_tester_i/HU/s_init_in_progress


TreeUpdate [SetDefaultTree]
quietly wave cursor active 2
configure wave -height 35
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue right
configure wave -signalnamewidth 1
configure wave -snapdistance 15
configure wave -datasetprefix 0
configure wave -rowmargin 10
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ps} {10000000 ps}


