######################################################################
##
## Filename: bram_sdp.udo
## Created on: Tue Jan 30 04:58:49 PM JST 2018
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
