######################################################################
##
## Filename: tb_top.udo
## Created on: Sun Feb 16 12:00:50 Северная Центр. Азия (зима) 2014
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb_top/CLK_50MHZ
add wave -noupdate /tb_top/OSC_50MHZ
add wave -noupdate /tb_top/RESET_P
add wave -noupdate /tb_top/SYS_RST
add wave -noupdate /tb_top/SDATAP
add wave -noupdate /tb_top/DCOP
add wave -noupdate /tb_top/FCOP
add wave -noupdate /tb_top/ADC_CLKP

add wave -noupdate -divider {SYSTEM_I}
add wave -noupdate /tb_top/uut/s_clock

add wave -noupdate -divider {INFRASTRUCTURE}

add wave -noupdate /tb_top/uut/infrastructure_top_i/RESET_N
add wave -noupdate /tb_top/uut/infrastructure_top_i/i_clock
add wave -noupdate /tb_top/uut/infrastructure_top_i/hb25ns

add wave -noupdate -divider {TOP}
add wave -noupdate /tb_top/uut/s_clk_cnt
add wave -noupdate /tb_top/uut/s_adc_buf_wnum
add wave -noupdate /tb_top/uut/s_adc_data
add wave -noupdate /tb_top/uut/s_buf_run
add wave -noupdate /tb_top/uut/s_lomtest_mode


add wave -noupdate -divider {ADC_CTRL}

add wave -noupdate /tb_top/uut/adc_ctrl_i/i_clock
add wave -noupdate /tb_top/uut/adc_ctrl_i/clock_locked
add wave -noupdate /tb_top/uut/adc_ctrl_i/s_clk_cnt
add wave -noupdate /tb_top/uut/adc_ctrl_i/s_vec_clk_div4
add wave -noupdate /tb_top/uut/adc_ctrl_i/o_adc_data
add wave -noupdate /tb_top/uut/adc_ctrl_i/s_adc_buf_we
add wave -noupdate /tb_top/uut/adc_ctrl_i/s_adc_buf_we_ctrl
add wave -noupdate /tb_top/uut/adc_ctrl_i/s_arr_adc_data
add wave -noupdate /tb_top/uut/adc_ctrl_i/s_arr_adc_data_sel
add wave -noupdate /tb_top/uut/adc_ctrl_i/s_arr_adc_data_w
add wave -noupdate /tb_top/uut/adc_ctrl_i/bitslip_reset
add wave -noupdate /tb_top/uut/adc_ctrl_i/i_testbuf_data
add wave -noupdate /tb_top/uut/adc_ctrl_i/s_adc_buf_wclk
add wave -noupdate /tb_top/uut/adc_ctrl_i/s_waddr
add wave -noupdate /tb_top/uut/adc_ctrl_i/o_testbuf_enable

add wave -noupdate -divider {ADC_DESER}

#add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_ADC_DESER(1)/adc_deser/i_clock
#add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_ADC_DESER(1)/adc_deser/s_clock_adc
#add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_ADC_DESER(1)/adc_deser/DCOP
#add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_ADC_DESER(1)/adc_deser/FCOP
#add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_ADC_DESER(1)/adc_deser/dco_divclk
#add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_ADC_DESER(1)/adc_deser/dco_strobe
#add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_ADC_DESER(1)/adc_deser/dco_ib
#add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_ADC_DESER(1)/adc_deser/data_sr
#add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_ADC_DESER(1)/adc_deser/serdes_q
#add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_ADC_DESER(1)/adc_deser/fco_serdes_q
#add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_ADC_DESER(1)/adc_deser/fco_serdes_q_r
#add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_ADC_DESER(1)/adc_deser/fco_serdes_q_dr
#add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_ADC_DESER(1)/adc_deser/bit_slip_r
#add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_ADC_DESER(1)/adc_deser/frame_start_r
#add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_ADC_DESER(1)/adc_deser/data_we_r
#add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_ADC_DESER(1)/adc_deser/adc_data_r
add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_ADC_DESER(1)/adc_deser/ADCNUM
add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_ADC_DESER(1)/adc_deser/DCON
add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_ADC_DESER(1)/adc_deser/DCOP
add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_ADC_DESER(1)/adc_deser/FCON
add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_ADC_DESER(1)/adc_deser/FCOP
add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_ADC_DESER(1)/adc_deser/SDATAN
add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_ADC_DESER(1)/adc_deser/SDATAP
add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_ADC_DESER(1)/adc_deser/bitslip
add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_ADC_DESER(1)/adc_deser/bitslip_reset
add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_ADC_DESER(1)/adc_deser/busy
add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_ADC_DESER(1)/adc_deser/cal_data
add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_ADC_DESER(1)/adc_deser/cal_done
add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_ADC_DESER(1)/adc_deser/cal_prog
add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_ADC_DESER(1)/adc_deser/clk_ddly_m
add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_ADC_DESER(1)/adc_deser/clk_ddly_s
add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_ADC_DESER(1)/adc_deser/ddly_m
add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_ADC_DESER(1)/adc_deser/ddly_s
add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_ADC_DESER(1)/adc_deser/del_rst
add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_ADC_DESER(1)/adc_deser/gclk
add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_ADC_DESER(1)/adc_deser/i_clock
add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_ADC_DESER(1)/adc_deser/mdata
add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_ADC_DESER(1)/adc_deser/q_frame
add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_ADC_DESER(1)/adc_deser/reset
add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_ADC_DESER(1)/adc_deser/rx_bufg_div4
add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_ADC_DESER(1)/adc_deser/rx_bufio2_div4
add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_ADC_DESER(1)/adc_deser/rx_clk_in_n
add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_ADC_DESER(1)/adc_deser/rx_clk_in_p
add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_ADC_DESER(1)/adc_deser/rx_data_in
add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_ADC_DESER(1)/adc_deser/rx_serdesstrobe
add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_ADC_DESER(1)/adc_deser/rxioclkn
add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_ADC_DESER(1)/adc_deser/rxioclkp
add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_ADC_DESER(1)/adc_deser/s_frame
add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_ADC_DESER(1)/adc_deser/s_frame_start
add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_ADC_DESER(1)/adc_deser/o_clock_adc
add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_ADC_DESER(1)/adc_deser/s_data
add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_ADC_DESER(1)/adc_deser/s_data_pre
add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_ADC_DESER(1)/adc_deser/o_data
add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_ADC_DESER(1)/adc_deser/o_data_we

add wave -noupdate -divider {BAD_ADC}

add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_ADC_DESER(1)/adc_deser/ADC_CHAN(6)/BAD_CHANNEL/SIMPLEDES/dco_ib_n
add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_ADC_DESER(1)/adc_deser/ADC_CHAN(6)/BAD_CHANNEL/SIMPLEDES/dco_ib_p
add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_ADC_DESER(1)/adc_deser/ADC_CHAN(6)/BAD_CHANNEL/SIMPLEDES/fco_ib
add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_ADC_DESER(1)/adc_deser/ADC_CHAN(6)/BAD_CHANNEL/SIMPLEDES/rx_data_in
add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_ADC_DESER(1)/adc_deser/ADC_CHAN(6)/BAD_CHANNEL/SIMPLEDES/o_data
add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_ADC_DESER(1)/adc_deser/ADC_CHAN(6)/BAD_CHANNEL/SIMPLEDES/s_data_we
add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_ADC_DESER(1)/adc_deser/ADC_CHAN(6)/BAD_CHANNEL/SIMPLEDES/s_data_r
add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_ADC_DESER(1)/adc_deser/ADC_CHAN(6)/BAD_CHANNEL/SIMPLEDES/s_data_dr
add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_ADC_DESER(1)/adc_deser/ADC_CHAN(6)/BAD_CHANNEL/SIMPLEDES/s_data
add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_ADC_DESER(1)/adc_deser/ADC_CHAN(6)/BAD_CHANNEL/SIMPLEDES/s_data_fco
add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_ADC_DESER(1)/adc_deser/ADC_CHAN(6)/BAD_CHANNEL/SIMPLEDES/s_data_fco_r
add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_ADC_DESER(1)/adc_deser/ADC_CHAN(6)/BAD_CHANNEL/SIMPLEDES/s_match
add wave -noupdate /tb_top/uut/adc_ctrl_i/GEN_ADC_DESER(1)/adc_deser/ADC_CHAN(6)/BAD_CHANNEL/SIMPLEDES/s_match_dr

add wave -noupdate -divider {REG}
add wave -noupdate /tb_top/uut/reg_file_m_i/s_reg_rdata(0)
add wave -noupdate /tb_top/uut/reg_file_m_i/s_reg_rdata(1)
add wave -noupdate /tb_top/uut/reg_file_m_i/s_reg_rdata(2)
add wave -noupdate /tb_top/uut/reg_file_m_i/s_reg_rdata(3)

add wave -noupdate -divider {LOM}
add wave -noupdate /tb_top/uut/lom_i/i_adc_thresholds
add wave -noupdate /tb_top/uut/lom_i/i_coi_thresholds
add wave -noupdate /tb_top/uut/lom_i/i_nevt
add wave -noupdate /tb_top/uut/lom_i/i_dead_time_max
add wave -noupdate /tb_top/uut/lom_i/i_discr_expand

add wave -noupdate /tb_top/uut/lom_i/i_clock
add wave -noupdate /tb_top/uut/lom_i/i_adc_data
add wave -noupdate /tb_top/uut/lom_i/s_arr_ampl
add wave -noupdate /tb_top/uut/lom_i/s_vec_hist_wena
add wave -noupdate /tb_top/uut/lom_i/s_vec_gate
add wave -noupdate /tb_top/uut/lom_i/s_vec_texp
add wave -noupdate /tb_top/uut/lom_i/s_vec_coin
add wave -noupdate /tb_top/uut/lom_i/s_vec_gate_sum
add wave -noupdate /tb_top/uut/lom_i/s_vec_sum_hit
add wave -noupdate /tb_top/uut/lom_i/s_vec_sumhist_wena
add wave -noupdate /tb_top/uut/lom_i/s_vec_texp_sum
add wave -noupdate /tb_top/uut/lom_i/s_hread_data
add wave -noupdate /tb_top/uut/lom_i/s_hread_addr
add wave -noupdate /tb_top/uut/lom_i/s_vec_coin_thr
add wave -noupdate /tb_top/uut/lom_i/o_bha_qua_cnt 
add wave -noupdate /tb_top/uut/lom_i/o_bha_raw_cnt 
add wave -noupdate /tb_top/uut/lom_i/o_clk_cnt
add wave -noupdate /tb_top/uut/lom_i/o_cmx_cnt
add wave -noupdate /tb_top/uut/lom_i/o_coi_cnt
add wave -noupdate /tb_top/uut/lom_i/o_ded_cnt
add wave -noupdate /tb_top/uut/lom_i/o_evt_cnt
add wave -noupdate /tb_top/uut/lom_i/o_lom_stat
add wave -noupdate /tb_top/uut/lom_i/o_roi_cnt
add wave -noupdate /tb_top/uut/lom_i/o_sum_cnt
add wave -noupdate /tb_top/uut/lom_i/s_BhabhaQua
add wave -noupdate /tb_top/uut/lom_i/s_BhabhaRaw
add wave -noupdate /tb_top/uut/lom_i/s_Bhabha_Qua_CNT
add wave -noupdate /tb_top/uut/lom_i/s_Bhabha_Raw_CNT
add wave -noupdate /tb_top/uut/lom_i/s_DT_GCNT
add wave -noupdate /tb_top/uut/lom_i/s_DeadTime
add wave -noupdate /tb_top/uut/lom_i/s_DeadTimeCNT
add wave -noupdate /tb_top/uut/lom_i/s_DeadTimeMAX
add wave -noupdate /tb_top/uut/lom_i/s_DeadTimeRaw
add wave -noupdate /tb_top/uut/lom_i/s_DeadTimeRawCNT
add wave -noupdate /tb_top/uut/lom_i/s_DeadTimeRawMAX
add wave -noupdate /tb_top/uut/lom_i/s_adc_cnt
add wave -noupdate /tb_top/uut/lom_i/s_adc_hit_dt
add wave -noupdate /tb_top/uut/lom_i/s_adc_hit_dt_cnt
add wave -noupdate /tb_top/uut/lom_i/s_adc_hit_or
add wave -noupdate /tb_top/uut/lom_i/s_arr_adc_amp
add wave -noupdate /tb_top/uut/lom_i/s_arr_adc_data
add wave -noupdate /tb_top/uut/lom_i/s_arr_adc_sums
add wave -noupdate /tb_top/uut/lom_i/s_arr_ampl
add wave -noupdate /tb_top/uut/lom_i/s_arr_sum_amp
add wave -noupdate /tb_top/uut/lom_i/s_arr_sum_ampl
add wave -noupdate /tb_top/uut/lom_i/s_coi_cnt
add wave -noupdate /tb_top/uut/lom_i/s_discr_expand
add wave -noupdate /tb_top/uut/lom_i/s_evt_cnt
add wave -noupdate /tb_top/uut/lom_i/s_nevt
add wave -noupdate /tb_top/uut/lom_i/s_roi_cnt
add wave -noupdate /tb_top/uut/lom_i/s_sum_cnt
add wave -noupdate /tb_top/uut/lom_i/s_vec_adc_hit
add wave -noupdate /tb_top/uut/lom_i/s_vec_coi
add wave -noupdate /tb_top/uut/lom_i/s_vec_coi_hit


add wave -noupdate /tb_top/uut/lom_i/o_adc_cnt
add wave -noupdate /tb_top/uut/lom_i/o_evt_cnt
add wave -noupdate /tb_top/uut/lom_i/o_coi_cnt
add wave -noupdate /tb_top/uut/lom_i/o_roi_cnt
add wave -noupdate /tb_top/uut/lom_i/o_sum_cnt
add wave -noupdate /tb_top/uut/lom_i/o_bha_raw_cnt
add wave -noupdate /tb_top/uut/lom_i/o_ded_qua_cnt

add wave -noupdate /tb_top/uut/lom_i/s_arr_adc_sums




add wave -noupdate -divider {DISCR}
add wave -noupdate /tb_top/uut/lom_i/ADC_GEN(1)/DU/i_clock
add wave -noupdate /tb_top/uut/lom_i/ADC_GEN(1)/DU/i_enable
add wave -noupdate /tb_top/uut/lom_i/ADC_GEN(1)/DU/i_input
add wave -noupdate /tb_top/uut/lom_i/ADC_GEN(1)/DU/i_texp
add wave -noupdate /tb_top/uut/lom_i/ADC_GEN(1)/DU/i_threshold
add wave -noupdate /tb_top/uut/lom_i/ADC_GEN(1)/DU/o_gate
add wave -noupdate /tb_top/uut/lom_i/ADC_GEN(1)/DU/o_texp
add wave -noupdate /tb_top/uut/lom_i/ADC_GEN(1)/DU/s_gate
add wave -noupdate /tb_top/uut/lom_i/ADC_GEN(1)/DU/s_start
add wave -noupdate /tb_top/uut/lom_i/ADC_GEN(1)/DU/s_tcnt

add wave -noupdate -divider {COINCIDENCE}
add wave -noupdate /tb_top/uut/lom_i/ADC_GEN(1)/CU_GEN/CU/i_clock
add wave -noupdate /tb_top/uut/lom_i/ADC_GEN(1)/CU_GEN/CU/i_run
add wave -noupdate /tb_top/uut/lom_i/ADC_GEN(1)/CU_GEN/CU/i_coidur_thresh
add wave -noupdate /tb_top/uut/lom_i/ADC_GEN(1)/CU_GEN/CU/i_signal_1
add wave -noupdate /tb_top/uut/lom_i/ADC_GEN(1)/CU_GEN/CU/i_signal_2
add wave -noupdate /tb_top/uut/lom_i/ADC_GEN(1)/CU_GEN/CU/o_coin
add wave -noupdate /tb_top/uut/lom_i/ADC_GEN(1)/CU_GEN/CU/o_coin_thr
add wave -noupdate /tb_top/uut/lom_i/ADC_GEN(1)/CU_GEN/CU/s_coin_meta
add wave -noupdate /tb_top/uut/lom_i/ADC_GEN(1)/CU_GEN/CU/o_coidur_we
add wave -noupdate /tb_top/uut/lom_i/ADC_GEN(1)/CU_GEN/CU/o_coidur
add wave -noupdate /tb_top/uut/lom_i/ADC_GEN(1)/CU_GEN/CU/s_coin_prev
add wave -noupdate /tb_top/uut/lom_i/ADC_GEN(1)/CU_GEN/CU/s_CoiDur_CNT
add wave -noupdate /tb_top/uut/lom_i/ADC_GEN(1)/CU_GEN/CU/s_coidur_we

add wave -noupdate -divider {AMPL}
add wave -noupdate /tb_top/uut/lom_i/ADC_GEN(1)/AU/i_clock
add wave -noupdate /tb_top/uut/lom_i/ADC_GEN(1)/AU/i_signal
add wave -noupdate /tb_top/uut/lom_i/ADC_GEN(1)/AU/i_gate
add wave -noupdate /tb_top/uut/lom_i/ADC_GEN(1)/AU/s_gate_prev
add wave -noupdate /tb_top/uut/lom_i/ADC_GEN(1)/AU/s_gate_next
add wave -noupdate /tb_top/uut/lom_i/ADC_GEN(1)/AU/o_wena
add wave -noupdate /tb_top/uut/lom_i/ADC_GEN(1)/AU/o_ampl

add wave -noupdate -divider {HIST}
add wave -noupdate /tb_top/uut/lom_i/HM/i_clock
add wave -noupdate /tb_top/uut/lom_i/HM/ADC_GEN(1)/AMPHIST/i_run
add wave -noupdate /tb_top/uut/lom_i/HM/ADC_GEN(1)/AMPHIST/i_wena
add wave -noupdate /tb_top/uut/lom_i/HM/ADC_GEN(1)/AMPHIST/s_wena
add wave -noupdate /tb_top/uut/lom_i/HM/ADC_GEN(1)/AMPHIST/s_wena_pre
add wave -noupdate /tb_top/uut/lom_i/HM/ADC_GEN(1)/AMPHIST/i_data
add wave -noupdate /tb_top/uut/lom_i/HM/ADC_GEN(1)/AMPHIST/i_raddr
add wave -noupdate /tb_top/uut/lom_i/HM/ADC_GEN(1)/AMPHIST/o_rdata
add wave -noupdate /tb_top/uut/lom_i/HM/ADC_GEN(1)/AMPHIST/histo_mem_i/mem
add wave -noupdate /tb_top/uut/lom_i/HM/ADC_GEN(1)/AMPHIST/s_bin_index
add wave -noupdate /tb_top/uut/lom_i/HM/ADC_GEN(1)/AMPHIST/s_bin_rindex
add wave -noupdate /tb_top/uut/lom_i/HM/ADC_GEN(1)/AMPHIST/s_bin_data
add wave -noupdate /tb_top/uut/lom_i/HM/ADC_GEN(1)/AMPHIST/s_bin_data_next
add wave -noupdate /tb_top/uut/lom_i/HM/ADC_GEN(1)/AMPHIST/s_bin_data_wr
add wave -noupdate /tb_top/uut/lom_i/HM/ADC_GEN(1)/AMPHIST/s_is_initialized
add wave -noupdate /tb_top/uut/lom_i/HM/ADC_GEN(1)/AMPHIST/s_init_in_progress

add wave -noupdate /tb_top/uut/lom_i/HM/SUM_GEN(1)/AMPHIST/i_clear 
add wave -noupdate /tb_top/uut/lom_i/HM/SUM_GEN(1)/AMPHIST/i_clock
add wave -noupdate /tb_top/uut/lom_i/HM/SUM_GEN(1)/AMPHIST/i_data
add wave -noupdate /tb_top/uut/lom_i/HM/SUM_GEN(1)/AMPHIST/i_raddr
add wave -noupdate /tb_top/uut/lom_i/HM/SUM_GEN(1)/AMPHIST/i_reset
add wave -noupdate /tb_top/uut/lom_i/HM/SUM_GEN(1)/AMPHIST/i_run
add wave -noupdate /tb_top/uut/lom_i/HM/SUM_GEN(1)/AMPHIST/i_test_mode
add wave -noupdate /tb_top/uut/lom_i/HM/SUM_GEN(1)/AMPHIST/i_wena
add wave -noupdate /tb_top/uut/lom_i/HM/SUM_GEN(1)/AMPHIST/o_overflow
add wave -noupdate /tb_top/uut/lom_i/HM/SUM_GEN(1)/AMPHIST/o_rdata
add wave -noupdate /tb_top/uut/lom_i/HM/SUM_GEN(1)/AMPHIST/s_bin_data
add wave -noupdate /tb_top/uut/lom_i/HM/SUM_GEN(1)/AMPHIST/s_bin_data_next
add wave -noupdate /tb_top/uut/lom_i/HM/SUM_GEN(1)/AMPHIST/s_bin_data_wr
add wave -noupdate /tb_top/uut/lom_i/HM/SUM_GEN(1)/AMPHIST/s_bin_index
add wave -noupdate /tb_top/uut/lom_i/HM/SUM_GEN(1)/AMPHIST/s_bin_index_next
add wave -noupdate /tb_top/uut/lom_i/HM/SUM_GEN(1)/AMPHIST/s_bin_rindex
add wave -noupdate /tb_top/uut/lom_i/HM/SUM_GEN(1)/AMPHIST/s_clear
add wave -noupdate /tb_top/uut/lom_i/HM/SUM_GEN(1)/AMPHIST/s_data
add wave -noupdate /tb_top/uut/lom_i/HM/SUM_GEN(1)/AMPHIST/s_init_in_progress
add wave -noupdate /tb_top/uut/lom_i/HM/SUM_GEN(1)/AMPHIST/s_is_initialized
add wave -noupdate /tb_top/uut/lom_i/HM/SUM_GEN(1)/AMPHIST/s_overflow
add wave -noupdate /tb_top/uut/lom_i/HM/SUM_GEN(1)/AMPHIST/s_wena
add wave -noupdate /tb_top/uut/lom_i/HM/SUM_GEN(1)/AMPHIST/s_wena_meta
add wave -noupdate /tb_top/uut/lom_i/HM/SUM_GEN(1)/AMPHIST/s_wena_pre



add wave -noupdate -divider {COIHIST}
add wave -noupdate /tb_top/uut/lom_i/HM/i_clock
add wave -noupdate /tb_top/uut/lom_i/HM/COI_GEN(1)/COIHIST/i_run
add wave -noupdate /tb_top/uut/lom_i/HM/COI_GEN(1)/COIHIST/i_wena
add wave -noupdate /tb_top/uut/lom_i/HM/COI_GEN(1)/COIHIST/s_wena
add wave -noupdate /tb_top/uut/lom_i/HM/COI_GEN(1)/COIHIST/i_data
add wave -noupdate /tb_top/uut/lom_i/HM/COI_GEN(1)/COIHIST/i_raddr
add wave -noupdate /tb_top/uut/lom_i/HM/COI_GEN(1)/COIHIST/o_rdata
add wave -noupdate /tb_top/uut/lom_i/HM/COI_GEN(1)/COIHIST/histo_mem_i/mem
add wave -noupdate /tb_top/uut/lom_i/HM/COI_GEN(1)/COIHIST/s_bin_index
add wave -noupdate /tb_top/uut/lom_i/HM/COI_GEN(1)/COIHIST/s_bin_rindex
add wave -noupdate /tb_top/uut/lom_i/HM/COI_GEN(1)/COIHIST/s_bin_data
add wave -noupdate /tb_top/uut/lom_i/HM/COI_GEN(1)/COIHIST/s_bin_data_next
add wave -noupdate /tb_top/uut/lom_i/HM/COI_GEN(1)/COIHIST/s_bin_data_wr

add wave -noupdate -divider {SELFTEST}
add wave -noupdate /tb_top/uut/self_tester_i/i_clock
add wave -noupdate /tb_top/uut/self_tester_i/i_enable
add wave -noupdate /tb_top/uut/self_tester_i/i_run
add wave -noupdate /tb_top/uut/self_tester_i/s_arr_adcdata
add wave -noupdate /tb_top/uut/self_tester_i/s_testbuf_addr
add wave -noupdate /tb_top/uut/self_tester_i/s_testbuf_addr_next
add wave -noupdate /tb_top/uut/self_tester_i/o_testbuf_data
add wave -noupdate /tb_top/uut/self_tester_i/i_nevents
add wave -noupdate /tb_top/uut/self_tester_i/s_events


add wave -noupdate -divider {COUNTER MANAGER}
add wave -noupdate /tb_top/uut/lom_i/CM/c_adc_cnt_zero
add wave -noupdate /tb_top/uut/lom_i/CM/c_coi_cnt_zero
add wave -noupdate /tb_top/uut/lom_i/CM/i_clear
add wave -noupdate /tb_top/uut/lom_i/CM/i_clock
add wave -noupdate /tb_top/uut/lom_i/CM/i_cnt_run
add wave -noupdate /tb_top/uut/lom_i/CM/i_evt_hit
add wave -noupdate /tb_top/uut/lom_i/CM/s_evt_cnt
add wave -noupdate /tb_top/uut/lom_i/CM/i_reset
add wave -noupdate /tb_top/uut/lom_i/CM/i_vec_adc_hit
add wave -noupdate /tb_top/uut/lom_i/CM/i_vec_coi_hit
add wave -noupdate /tb_top/uut/lom_i/CM/i_vec_dur_hit
add wave -noupdate /tb_top/uut/lom_i/CM/o_adc_cnt
add wave -noupdate /tb_top/uut/lom_i/CM/o_clk_cnt
add wave -noupdate /tb_top/uut/lom_i/CM/o_coi_cnt
add wave -noupdate /tb_top/uut/lom_i/CM/o_dur_cnt
add wave -noupdate /tb_top/uut/lom_i/CM/o_evt_cnt
add wave -noupdate /tb_top/uut/lom_i/CM/s_adc_cnt
add wave -noupdate /tb_top/uut/lom_i/CM/s_clk_cnt
add wave -noupdate /tb_top/uut/lom_i/CM/s_coi_cnt
add wave -noupdate /tb_top/uut/lom_i/CM/s_dur_cnt

add wave -noupdate /tb_top/clk_cnt


TreeUpdate [SetDefaultTree]
quietly wave cursor active 2
configure wave -height 35
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue right
configure wave -signalnamewidth 1
configure wave -snapdistance 15
configure wave -datasetprefix 0
configure wave -rowmargin 10
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ps} {10000000 ps}


